Internet_Banking/Controllers/PagosController.cs
using Core.Application.Dtos.Account;
using Core.Application.Dtos.Pagos;
using Core.Application.Enums;
using Core.Application.Interfaces.Services;
using Core.Application.ViewModels.Pagos;
using Core.Application.ViewModels.Pagos.PagosBeneficiarios;
using Core.Application.ViewModels.Pagos.PagosExpresos;
using Core.Application.ViewModels.Pagos.PagosTarjetaCredito;
using Core.Application.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Asn1.X509;
using SocialMedia.Middlewares;

namespace Internet_Banking.Controllers
{
    [Authorize(Roles = "Basic, SuperAdmin")]
    public class PagosController : Controller
    {
        private readonly ICuentaAhorroService _cuentaAhorroService;
        private readonly IPrestamoService _prestamoService;
        private readonly ValidateUserSession _validateUser;
        private readonly ITarjetaCreditoService _tarjetaCreditoService;
        private readonly IPagosService _pagosService;
        private readonly IBeneficiarioService _beneficiarioService;

        AuthenticationResponse _user;
        public PagosController(ICuentaAhorroService cuentaAhorro, ValidateUserSession validateUserSession, 
            IPagosService pagosService, IPrestamoService prestamoService, ITarjetaCreditoService tarjetaCreditoService,
            IBeneficiarioService beneficiarioService)
        {
            _cuentaAhorroService = cuentaAhorro;
            _validateUser = validateUserSession;
            _pagosService = pagosService;
            _prestamoService = prestamoService;
            _beneficiarioService = beneficiarioService;

            _user = _validateUser.UserLoggedIn();
            _tarjetaCreditoService = tarjetaCreditoService;
        }

        public async Task<IActionResult> Index()
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

            ViewBag.listaTarjetas = await _tarjetaCreditoService.GetAllTarjetaById(_user.Id);

            ViewBag.listaPrestamos = await _prestamoService.GetAllPrestamosById(_user.Id);

            ViewBag.listaBeneficiarios = await _beneficiarioService.GetAllViewModelWithInclude(_user.Id);

            return View();
        }

        #region pagoExpresos

        [HttpPost]
        public IActionResult PagosExpresosGetCuenta(string cuenta)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            SavePagoExpresoViewModel pago = new();
            pago.NumeroCuentaOrigen = cuenta;

            return View("PagosExpreso/PagosExpresos", pago);
        }

        [HttpPost]
        public async Task<IActionResult> PagosExpresos(SavePagoExpresoViewModel vm)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            if (!ModelState.IsValid)
            {
                return View("PagosExpreso/PagosExpresos", vm);
            }

            PagoExpressResponse response = await _pagosService.PagoExpress(vm);

            if (response.HasError)
            {
                vm.HasError = true;
                vm.Error = response.Error;

                return View("PagosExpreso/PagosExpresos", vm);
            }

            return RedirectToAction("PagoExpresoDetails", response);
        }

        public IActionResult PagoExpresoDetails(PagoExpressResponse response)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            return View("PagosExpreso/PagoExpresoDetails", response);
        }

        [HttpPost]
        public async Task<IActionResult> PagosExpresoConfirm(PagoExpressResponse vm)
        {

            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            PagoConfirmedViewModel response = await _pagosService.PagosExpresoConfirmed(vm);


            if (response.HasError)
            {
                vm.HasError = true;
                vm.Error = vm.Error;

                return View("PagosExpreso/PagoExpresoDetails", vm);
            }

            return RedirectToAction("PagoConfirmed", response);
        }

        #endregion


        #region pagoTarjetaCredito
        
        public async Task<IActionResult> GetAllTarjetas(string productId)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

            SavePagoTarjetaViewModel vm = new();
            vm.idProduct = productId;

            return View("PagoTarjetaCredito/EnvioPagoTarjeta", vm);
        }

        [HttpPost]
        public async Task<IActionResult> EnvioPagoTarjetaPost(SavePagoTarjetaViewModel vm)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            if (!ModelState.IsValid)
            {
                ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

                return View("PagoTarjetaCredito/EnvioPagoTarjeta", vm);
            }

            var response = await _pagosService.SendPaymentTarjeta(vm);

            if (response.HasError == true)
            {
                ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

                if (response.Error == "Usted aun no debe esta tarjeta!")
                {
                    return View("PagoTarjetaCredito/ErrorMessage", response);
                }

                return View("PagoTarjetaCredito/EnvioPagoTarjeta", vm);
            }

            PagoConfirmedViewModel resultado = new();

            resultado.isTarjetaCredito = true;

            resultado.FirstNameOrigen = response.FirstNameOrigen;
            resultado.LastNameOrigen = response.LastNameOrigen;
            resultado.LastTarjetaCredito = response.LastTarjetaCredito;
            resultado.Monto = response.Monto;
            resultado.NumeroCuentaOrigen = response.NumeroCuentaOrigen;
            resultado.TransactionId = response.TransactionId;

            return RedirectToAction("PagoConfirmed", resultado);
        }

        #endregion

        #region pagoPrestamo

        public async Task<IActionResult> GetAllPrestamos(string productId)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }




            ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

            SavePagoPrestamoViewModel vm = new();
            vm.idProduct = productId;

            return View("PagosPrestamo/EnvioPagoPrestamo", vm);
        }

        [HttpPost]
        public async Task<IActionResult> EnvioPagoPrestamoPost(SavePagoPrestamoViewModel vm)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            if (!ModelState.IsValid)
            {
                ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

                return View("PagosPrestamo/EnvioPagoPrestamo", vm);
            }

            var response = await _pagosService.SendPaymentPrestamo(vm);

            if (response.HasError == true)
            {
                vm.HasError = response.HasError;
                vm.Error = response.Error;

                ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

                return View("PagosPrestamo/EnvioPagoPrestamo", vm);
            }

            PagoConfirmedViewModel resultado = new();

            resultado.isPrestamo = true;

            resultado.FirstNameOrigen = response.FirstNameOrigen;
            resultado.LastNameOrigen = response.LastNameOrigen;

Internet_Banking/Views/Pagos/PagosPrestamo/EnvioPagoPrestamo.cshtml
@using Core.Application.ViewModels.Pagos;
@using Core.Application.ViewModels.CuentaAhorros;

@model SavePagoPrestamoViewModel
@{
    ViewData["Title"] = "Pagos prestamo";
}

<div class="col-12 d-flex justify-content-center">
    <div class="col-5 mt-5">
        <form method="post" asp-action="EnvioPagoPrestamoPost" asp-controller="Pagos">
            <div class="card">
                <div class="card-header">
                    <h4>Pagos Prestamos</h4>
                </div>
                <div class="card-body">
                    @Html.ValidationSummary(false, "", new{@class = "text-danger"})

                    @if (Model.HasError == true)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <p>@Model.Error</p>
                            <a class="btn btn-close" data-bs-dismiss="alert" arial-label="Close"></a>
                        </div>
                    }

                    <div class="form-outline mb-4">
                        <input hidden asp-for="idProduct" value="@Model.idProduct" class="form-control" />
                    </div>

                    <div class="form-outline mb-4">
                        <label asp-for="NumeroCuentaOrigen" class="form-label">Cuenta Origen:</label>
                        <select class="form-select" asp-for="NumeroCuentaOrigen">
                            @foreach (CuentaAhorroViewModel item in ViewBag.listaCuentasAhorro)
                            {
                                <option value="@item.NumeroCuenta">@item.NumeroCuenta || $@item.Balance</option>
                            }
                        </select>
                    </div>

                    <div class="form-outline mb-4">
                        <label asp-for="Monto" class="form-label">Monto:</label>
                        <input class="form-control" asp-for="Monto" step="any" min="100" id="montoInput" placeholder="Monto">
                    </div>

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-success btn-block mb-3">Enviar pago</button>
                </div>
            </div>
        </form>
    </div>
</div>


@section scripts{
    <script>

        function commaOnly(input) {

            var value = input.val();
            var values = value.split("");
            var update = "";
            var transition = "";

            var expression = /(^\d+$)|(^\d+\.\d+$)|[,\.]/;
            var finalExpression = /^([1-9][0-9]*[,\.]?\d{0,3})$/;

            for (id in values) {
                if (expression.test(values[id]) == true && values[id] != '') {
                    transition += '' + values[id].replace('.', ',');
                    if (finalExpression.test(transition) == true) {
                        update += '' + values[id].replace('.', ',');
                    }
                }
            }
            input.val(update);
        }

        $('#montoInput').keyup(function (e) {
            commaOnly($(this));
        });

    </script>


}