Internet_Banking/Controllers/ManageUserController.cs
using Core.Application.Dtos.Account;
using Core.Application.Interfaces.Services;
using Core.Application.ViewModels.CuentaAhorros;
using Core.Application.ViewModels.Prestamos;
using Core.Application.ViewModels.TarjetaCreditos;
using Core.Application.ViewModels.Transactions;
using Infrastructure.Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SocialMedia.Middlewares;

namespace Internet_Banking.Controllers
{
    [Authorize(Roles = "SuperAdmin, Admin")]
    public class ManageUserController : Controller
    {
        private readonly IDashboradService _dashboradService;
        private readonly ICuentaAhorroService _cuentaAhorro;
        private readonly IProductService _productService;
        private readonly IManageUserService _manageUserService;
        private readonly IPrestamoService _prestamoService;
        private readonly ValidateUserSession _validateUser;

        public ManageUserController(IDashboradService dashboradService, ICuentaAhorroService cuentaAhorro,
            IProductService service, IManageUserService manageUserService, IPrestamoService servicePrestamo
          ,ValidateUserSession userSession)
        {
            _dashboradService = dashboradService;
            _cuentaAhorro = cuentaAhorro;
            _productService = service;
            _manageUserService = manageUserService;
            _prestamoService = servicePrestamo;
            _validateUser = userSession;
        }

        public async Task<IActionResult> Index()
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }



            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();
          

            return View(new AuthenticationResponse());
        }

        public async Task<IActionResult> ActivateUser(string Id)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            await _dashboradService.ActivateUser(Id);
            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            return View("Index", new AuthenticationResponse());
        }

        public async Task<IActionResult> DesactivateUser(string Id)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            await _dashboradService.DesactiveUser(Id);
            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            return View("Index", new AuthenticationResponse());
        }

        [HttpPost]
        public async Task<IActionResult> GetUserByEmail(AuthenticationResponse userResponse)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            AuthenticationResponse userGot = new();

            if (userResponse.Email != null)
            {
                userGot = await _dashboradService.GetUserByEmail(userResponse.Email);
            }

            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            return View("Index", userGot);
        }

        public async Task<IActionResult> ProductSelector(string Id, string name, bool status)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            ViewBag.UserId = Id;
            ViewBag.UserName = name;
            ViewBag.Status = status;

            ViewBag.lista = await _manageUserService.gettinProductsById(Id);

            return View("ProductSelector");
        }

        public async Task<IActionResult> ManageClientProducts(string Id, string name, bool status)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            if (status == false) // Si el usuario no esta activo no se le pueden agregar productos
            {
                RedirectToAction("ErrorMessage");
            }
            if (!ModelState.IsValid)
            {
                return View("ManageClientProducts");
            }

            var cuenta = new SaveCuentaAhorroViewModel();

            cuenta.UserId = Id;
            ViewBag.UserName = name;

            return View(cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> ManageClientProducts(SaveCuentaAhorroViewModel cuentaVm)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            await _cuentaAhorro.Add(cuentaVm, cuentaVm.UserId, false);

            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            return View("Index", new AuthenticationResponse());
        }

        public async Task<IActionResult> DeleteCuentaById(string Id, double CuentaMonto, string tipo) //DELETE PRODUCT* BY ID
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }


            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            await _manageUserService.DeletingCuentaAhorro(Id, CuentaMonto, tipo);

            return View("Index", new AuthenticationResponse());
        }

        public async Task<IActionResult> ManageTarjetaCredito(string Id)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            if (Id != "")
            {
                ViewBag.UserId = Id;
            }

            return View(new SaveTarjetaCreditoViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> ManageTarjetaCredito(SaveTarjetaCreditoViewModel tarjetaVm)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            await _manageUserService.ManageTarjetaCredito(tarjetaVm);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ManagePrestamo(string UserId)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            var prestamoObj = new SavePrestamoViewModel();

            ViewBag.UserId = UserId;

            return View(prestamoObj);
        }

        [HttpPost]
        public async Task<IActionResult> ManagePrestamo(SavePrestamoViewModel prestamoVm, string UserId)
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });
            }

            if (!_validateUser.IsAdmin())
            {
                return RedirectToRoute(new { Controller = "Home", Action = "Index" });
            }

            var prestamoObj = new SavePrestamoViewModel();
            
            ViewBag.usersList = await _dashboradService.getAllUsersAndInformation();

            var prestamoFinal = await _prestamoService.AddCuentaAhorro(prestamoVm, UserId);

            await _manageUserService.addPrestamoToUser(prestamoFinal, UserId);

            return View("Index", new AuthenticationResponse());
        }

        public async Task<IActionResult> ErrorMessage()
        {
            if (!_validateUser.HasUser())
            {
                return RedirectToRoute(new { Controller = "User", Action = "Index" });

Internet_Banking/Views/ManageUser/ErrorMessage.cshtml
<h4 class="mx-auto text-center text-danger bg-primary">Este usuario no esta activo para administrar sus productos</h4>

<a asp-controller="ManageUser" asp-action="Index" class="btn btn-info">Volver atras</a>

Internet_Banking/Views/ManageUser/Index.cshtml
@using Core.Application.Dtos.Account


@model AuthenticationResponse

<div class="col-11 d-flex offset-1">
    <div class="w-100">

        <div class="w-100 d-flex mb-5 align-items-center border border-2">
            <h2 class="fs-2">Manage user Home page</h2>

            <div class="w-50 d-flex justify-content-end">
                <a class="btn btn-success" asp-controller="User" asp-action="Register" asp-route-editing="@false">Crear usuario</a>
            </div>
        </div>



        <div class="w-100 justify-content-end d-flex align-items-center border border-1 mb-3">

            <h5 class="me-2">Buscar usuario por correo:</h5>
            <form class="d-flex align-items-center align-content-center" method="post" asp-controller="ManageUser" asp-action="GetUserByEmail">
                <input class="me-2 form-control" type="text" asp-for="Email">
                <button class="btn btn-success me-2" type="submit">Buscar</button>
            </form>

            <a asp-action="Index" asp-controller="ManageUser" class="btn btn-warning">Limpiar busqueda</a>
        </div>


        <h4>Lista de usuarios</h4>
        <div class="w-100 d-flex flex-wrap">
            @if (Model.Id == null || Model.Id == "")
            {
                @foreach (AuthenticationResponse item in ViewBag.usersList)
                {
                    <div class="border border-2 border-red rounded m-2 p-2 d-flex justify-content-center align-items-center flex-column" style="max-width: 400px;">
                        <div>
                            <p class="text-center font-weight-bold">nombre: @item?.FirstName</p>
                            <p class="text-center font-weight-bold">Usuario: @item?.UserName</p>
                            <p class="text-center font-weight-bold">Correo: @item?.Email</p>
                            <p class="text-center font-weight-bold">Estado: @(item?.Status == false ? "Desactivado" : "Activo")</p>
                            @if (item?.Roles != null)
                            {
                                foreach (var x in item.Roles)
                                {
                                    <p class="text-center">Tipo de usuario: @(x == "Basic" ? "Basico" : "Administrador")</p>
                                }
                            }
                        </div>

                        <div>
                            @if (@item.Status)
                            {
                                <a class="btn btn-primary" asp-action="DesactivateUser" asp-controller="ManageUser" asp-route-Id="@item?.Id">Desactivar</a>
                            }
                            else
                            {
                                <a class="btn btn-primary" asp-action="ActivateUser" asp-controller="ManageUser" asp-route-Id="@item?.Id">Activar</a>
                            }
                            <a class="btn btn-primary" asp-controller="User" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                            <a class="btn btn-primary" asp-action="ProductSelector" asp-controller="ManageUser" asp-route-Id="@item?.Id" asp-route-name="@item?.FirstName" asp-route-status="@item?.Status">Productos</a>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="border border-2 border-red rounded m-2 p-2 d-flex justify-content-center align-items-center flex-column" style="max-width: 400px;">
                    <div>
                        <p class="text-center font-weight-bold">Nombre: @Model?.FirstName</p>
                        <p class="text-center font-weight-bold">Usuario: @Model?.UserName</p>
                        <p class="text-center font-weight-bold">Email: @Model?.Email</p>
                        <p class="text-center font-weight-bold">Estado: @(Model?.Status == false ? "Desactivado" : "Activo")</p>
                        @if (Model?.Roles != null)
                        {
                            foreach (var item in Model?.Roles)
                            {
                                <p class="text-center">Tipo de usuario: @(item == "Basic" ? "Basico" : "Administrador")</p>
                            }
                        }
                    </div>

                    <div>
                        @if (Model.Status)
                        {
                            <a class="btn btn-primary" asp-action="DesactivateUser" asp-controller="ManageUser" asp-route-Id="@Model?.Id">Desactivar</a>
                        }
                        else
                        {
                            <a class="btn btn-primary" asp-action="ActivateUser" asp-controller="ManageUser" asp-route-Id="@Model?.Id">Activar</a>
                        }
                        <a class="btn btn-primary" asp-controller="User" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
                        <a class="btn btn-primary" asp-action="ProductSelector" asp-controller="ManageUser" asp-route-Id="@Model?.Id" asp-route-name="@Model?.FirstName" asp-route-status="@Model?.Status">Productos</a>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

Internet_Banking/Views/ManageUser/ManageClientProducts.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Core.Application.ViewModels.CuentaAhorros;
@using Core.Application.ViewModels.Products
@model SaveCuentaAhorroViewModel
@{
    var userName = ViewBag.UserName;
}

<form class="mx-auto border border-1 border-secondary rounded-2" style="max-width: 450px;" method="post" asp-action="ManageClientProducts" asp-controller="ManageUser">
    <div class="d-flex flex-column justify-content-center align-content-center p-1 m-1">
        <h4 class="m-1">Agregar cuenta de ahorro a: @userName</h4>
        
        <label asp-for="Balance" class="form form-label">Monto de la cuenta de ahorro:</label>
        <input type="number" required class="form form-control m-1" asp-for="Balance" value="">
        <input type="hidden" asp-for="UserId" value="@Model.UserId">

        <button type="submit" class="btn btn-primary m-1">Crear</button>
        <a class="btn btn-danger m1" asp-action="Index" asp-controller="ManageUser">Cancelar</a>
    </div>
</form>

Internet_Banking/Views/ManageUser/ManagePrestamo.cshtml
@using Core.Application.ViewModels.Prestamos;
@model SavePrestamoViewModel
@{
    var userId = ViewBag.UserId;
}

<form class="mx-auto border border-1 border-secondary rounded-2" style="max-width: 450px;" method="post" asp-action="ManagePrestamo" asp-controller="ManageUser" asp-route-UserId="@userId">
    <div class="d-flex flex-column justify-content-center align-content-center p-1 m-1">
        <h2 class="m-1"> Prestamo Clientes </h2>
        <label asp-for="Monto" class="m-1 form form-label">Monto del prestamo</label>
        <input class="form form-control m-1" type="number" required value="" asp-for="Monto">
        
        <button class="btn btn-primary m-1">Obtener prestamo</button> 
        <a class="btn btn-danger m1" asp-action="Index" asp-controller="ManageUser">Cancelar</a>
    </div>
</form>

Internet_Banking/Views/ManageUser/ManageTarjetaCredito.cshtml
@using Core.Application.ViewModels.TarjetaCreditos;
@model SaveTarjetaCreditoViewModel
@{
    var userId = ViewBag.UserId;
}



<form class="mx-auto border border-1 border-secondary rounded-2" style="max-width: 450px;" method="post" asp-action="ManageTarjetaCredito" asp-controller="ManageUser">
    <div class="d-flex flex-column justify-content-center align-content-center p-1 m-1">
    <h4 class="m-1">Solicitud tarjeta de credito</h4>
        <label asp-for="Limite" class="form form-label"> Seleccione un monto limite para la tarjeta de credito: </label>
        <select asp-for="Limite" class="form form-select mb-2">
            <option value="10000">$10,000</option>
            <option value="15000">$15,000</option>
            <option value="20000">$20,000</option>
            <option value="30000">$30,000</option>
            <option value="40000">$40,000</option>
            <option value="50000">$50,000</option>
            <option value="60000">$60,000</option>
        </select>
        <input type="hidden" asp-for="UserId" value="@ViewBag.UserId" />
        <input type="hidden" asp-for="Debe" value="0" />
        <input type="hidden" asp-for="Balance" value="0"/>
        <input type="hidden" asp-for="Pago" value="0" />
        <input type="hidden" asp-for="IdProduct" value="@null" />
        
        <button type="submit" class="btn btn-primary m-1">Agregar tarjeta de credito</button>
        <a class="btn btn-danger m1" asp-action="Index" asp-controller="ManageUser">Cancelar</a>
    </div>
</form>

Internet_Banking/Views/ManageUser/ProductSelector.cshtml
@using Core.Application.ViewModels.Products



<h2>Selecciona el producto que quieres agregar al usuario</h2>

<div class="mx-auto" style="max-width: 450px;">
    <div style="max-width: 400px" class="border rounded d-flex justify-content-center align-items-center p-2 m-2">
        <a class="btn btn-primary m-2" asp-controller="ManageUser" 
           asp-action="ManageClientProducts" 
           asp-route-status="@ViewBag.Status"
           asp-route-name="@ViewBag.UserName"
           asp-route-Id="@ViewBag.UserId">Cuentas</a>
        
        <a class="btn btn-primary m-2" asp-controller="ManageUser"
           asp-action="ManageTarjetaCredito"
           asp-route-Id="@ViewBag.UserId">Tarjetas</a>
        
        <a class="btn btn-primary m-2" asp-controller="ManageUser"
           asp-action="ManagePrestamo"
           asp-route-UserId="@ViewBag.UserId">Prestamo</a>
    </div>
</div>

<div class="border border-1 m-1 p1">
    <h4>Lista de productos de @ViewBag.UserName</h4>
    
    
    <div class="d-flex justify-content-center border border-5 flex-wrap">
        
        @foreach (ProductViewModel item in ViewBag.lista)
        {
            if (item.CuentaAhorros != null)
            {
                <div class="text-white d-flex flex-column align-items-center justify-content-center border border-1 m-2 p-2 rounded bg-dark">
                    <h2><strong>Cuenta de ahorro</strong></h2>
                    <div>
                        <h4>Numero de cuenta: @item.CuentaAhorros.NumeroCuenta</h4>
                        <h4>@(item.CuentaAhorros.Principal == true ? "Cuenta Principal" : "Cuenta Secundaria")</h4>
                        <h4>Balance: @item.CuentaAhorros.Balance</h4>
                    </div>
                    @if (@item.CuentaAhorros.Principal == false)
                    {
                        <a class="btn btn-danger" asp-action="DeleteCuentaById" asp-controller="ManageUser" asp-route-Id="@item.Id" asp-route-CuentaMonto="@item.CuentaAhorros.Balance" asp-route-tipo="Ahorro">Eliminar</a>
                    }
                </div>
            }
        }
        @foreach (ProductViewModel item in ViewBag.lista)
        {
            if (item.TarjetaCreditos != null)
            {
                <div class="text-white d-flex flex-column align-items-center justify-content-center border border-1 border-danger m-2 p-2 rounded bg-dark">
                    <h2><strong>Tarjeta de credito</strong></h2>
                    <div>
                        <h4>Numero de terjeta: @item.TarjetaCreditos.NumeroTarjeta</h4>
                        <h4>Limite: @item.TarjetaCreditos.Limite</h4>
                        <h4>Debe: @item.TarjetaCreditos.Debe</h4>
                        <h4>Pago: @item.TarjetaCreditos.Pago</h4>
                    </div>
                    <a class="btn btn-danger" asp-action="DeleteCuentaById" asp-controller="ManageUser" asp-route-Id="@item.Id" asp-route-CuentaMonto="@item.TarjetaCreditos.Limite" asp-route-tipo="Tarjeta">Eliminar</a>
                </div>
            }
        }
        @foreach (ProductViewModel item in ViewBag.lista)
        {
            if (item.Prestamos != null)
            {
                <div class="text-white d-flex flex-column align-items-center justify-content-center border border-1 border-danger m-2 p-2 rounded bg-dark">
                    <h2><strong>Prestamos</strong></h2>
                    <div>
                        <h4>Numero de prestamo: @item.Prestamos.NumeroPrestamo</h4>
                        <h4>Monto: @item.Prestamos.Monto</h4>
                        <h4>Debe: @item.Prestamos.Debe</h4>
                        <h4>Pago: @item.Prestamos.Pago</h4>
                    </div>
                    <a class="btn btn-danger" asp-action="DeleteCuentaById" asp-controller="ManageUser" asp-route-Id="@item.Id" asp-route-CuentaMonto="@item.Prestamos.Balance" asp-route-tipo="Prestamo">Eliminar</a>
                </div>
            }
        }

    </div>
</div>