Internet_Banking/Controllers/AvanzeEfectivoController.cs
using Core.Application.Dtos.Account;
using Core.Application.Dtos.Pagos;
using Core.Application.Interfaces.Services;
using Core.Application.ViewModels.Pagos.PagoAvance;
using Microsoft.AspNetCore.Mvc;
using SocialMedia.Middlewares;

namespace Internet_Banking.Controllers;

public class AvanzeEfectivoController : Controller
{

    private readonly ITarjetaCreditoService _tarjetaCreditoService;
    private readonly ValidateUserSession _validateUserSession;
    private readonly IPagosService _pagosService;
    private readonly ICuentaAhorroService _cuentaAhorroService;
    
    AuthenticationResponse _user;
    
    public AvanzeEfectivoController(ICuentaAhorroService cuentaAhorroService, IPagosService pagosService,
        ValidateUserSession validateUserSession, ITarjetaCreditoService tarjetaCreditoService  )
    {
        _tarjetaCreditoService = tarjetaCreditoService;
        _pagosService = pagosService;
        _validateUserSession = validateUserSession;
        _cuentaAhorroService = cuentaAhorroService;
        
        _user = _validateUserSession.UserLoggedIn();
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.GetAllTarjetaCreditos = await _tarjetaCreditoService.GetAllTarjetaById(_user.Id);
        ViewBag.GetAllCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

        return View();
    }

    public async Task<IActionResult> AvanzeEfectivo(string numeroTarjeta, string idTarjeta, double LimiteTarjeta, string IdProduct)
    {
        if (!_validateUserSession.HasUser())
        {
            RedirectToRoute(new {controller = "User", action = "Index"});
        }

        ViewBag.GetAllTarjetaCreditos = await _tarjetaCreditoService.GetAllTarjetaById(_user.Id);

        ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

        SavePagoAvanceViewModel vm = new();
        vm.NumeroTarjetaCredito = numeroTarjeta;
        vm.idTarjetaCredito = idTarjeta;
        vm.TarjetaMonto = LimiteTarjeta;
        vm.IdProduct = IdProduct;

        return View("SaveAvanzeEfectivo", vm);
    }
    
    [HttpPost]
    public async Task<IActionResult> SaveAvanzeEfectivo(SavePagoAvanceViewModel vm)
    {
        if (!_validateUserSession.HasUser())
        {
            RedirectToAction("SaveAvanzeEfectivo", vm);
        }

        ViewBag.GetAllTarjetaCreditos = await _tarjetaCreditoService.GetAllTarjetaById(_user.Id);

        ViewBag.GetAllCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);
        
        var response = await _pagosService.GetAvancePago(vm);
        
        if (response.HasError == true)
        {
            vm.HasError = response.HasError;
            vm.Error = response.Error;

            ViewBag.listaCuentasAhorro = await _cuentaAhorroService.GetAllViewModelWithInclude(_user.Id);

            return View("SaveAvanzeEfectivo", vm);
        }

        PagoAvanceEfectivoResponse resultado = new();
        
        resultado.FirstNameOrigen = response.FirstNameOrigen;
        resultado.LastNameOrigen = response.LastNameOrigen;
        resultado.NumeroTarjeta = response.NumeroTarjeta;
        resultado.Monto = response.Monto;
        resultado.NumeroCuenta = response.NumeroCuenta;
        resultado.MontoCargado = response.MontoCargado;

        return RedirectToAction("MontoRetiradoConfirmed", response);
    }
    
    public IActionResult MontoRetiradoConfirmed(PagoAvanceEfectivoResponse response)
    {
        return View(response);
    }
}

Internet_Banking/Views/AvanzeEfectivo/Index.cshtml
@using Core.Application.ViewModels.TarjetaCreditos; 
@model TarjetaCreditoViewModel
@{
    
}

<div class="col-11 d-flex m-4">

    @foreach (TarjetaCreditoViewModel item in ViewBag.GetAllTarjetaCreditos)
    {
        <form method="post" asp-controller="AvanzeEfectivo" asp-action="AvanzeEfectivo">
            <div class="card me-1">
                <div class="card-header d-flex">
                    <p class="me-1">@item.NumeroTarjeta</p>
                </div>
    
                <div class="card-body">
                    <p><strong>Monto establecido para la tarjeta: </strong> @item.Limite</p>
                    <p><strong>Debe: </strong> @item.Debe</p>
                    <p><strong>Pagos: </strong> @item.Pago</p>
                </div>
                
                <input hidden value="@item.NumeroTarjeta" name="numeroTarjeta">
                <input hidden value="@item.Id" name="idTarjeta">
                <input hidden value="@item.Limite" name="LimiteTarjeta">
                <input hidden value="@item.Idproduct" name="IdProduct">
    
                <div class="card-footer">
    
                    <!-- Modal -->
                    <button class="btn btn-warning" type="submit">Avanze de efectivo</button>
                </div>
            </div>
        </form>
    }
</div>

Internet_Banking/Views/AvanzeEfectivo/MontoRetiradoConfirmed.cshtml
@using Core.Application.ViewModels.Pagos
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Core.Application.Dtos.Pagos;
@model PagoAvanceEfectivoResponse
@{
    ViewData["Title"] = "Confirmacion de retiro tarjeta";
}
@section scripts {
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'Transaccion confirmada!',
            showConfirmButton: false,
            timer: 2000
        })
    </script>
}

<div class="col-12 d-flex justify-content-center">
    <div class="col-5 mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Avance efectivo</h2>
            </div>
            <div class="card-body">
                
                <div class="form-outline mb-4">
                    <h3>Retiro realizado por:</h3>
                    <label>@Model.FirstNameOrigen @Model.LastNameOrigen</label>
                </div>

                <div class="form-outline mb-4">
                    <h3>Num tarjeta</h3>
                    <label>@Model.NumeroTarjeta</label>
                </div>

                <div class="form-outline mb-4">
                    <h3 class="me-2">Monto Retirado de la tarjeta</h3>
                    <label>$@Model.Monto</label>
                </div>
            
                <div class="form-outline mb-4">
                    <h3 class="me-2">Monto Cargado a la deuda de la tarjeta</h3>
                    <label>$@Model.MontoCargado</label>
                </div>
                
                <div class="form-outline mb-4">
                    <h3 class="me-2">Cuenta de ahorro a la que deposito:</h3>
                    <label>$@Model.oldMontoCuenta ----> $@Model.newMontoCuenta</label>
                </div>

                <a asp-action="Index" asp-controller="Home" class="btn btn-secondary btn-block mb-3">Volver al home</a>
            </div>
        </div>
    </div>
</div>

Internet_Banking/Views/AvanzeEfectivo/SaveAvanzeEfectivo.cshtml
@using Core.Application.ViewModels.CuentaAhorros
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Core.Application.ViewModels.Pagos.PagoAvance;
@model SavePagoAvanceViewModel
@{
    ViewData["Title"] = "Avance efectivo";
}

<div class="col-12 d-flex justify-content-center">
    <div class="col-5 mt-5">
        <form method="post" asp-action="SaveAvanzeEfectivo" asp-controller="AvanzeEfectivo">
            <div class="card">
                <div class="card-header">
                    <h4>Avance de efectivo</h4>
                </div>
                <div class="card-body">
                    @Html.ValidationSummary(false, "", new{@class = "text-danger"})

                    @if (Model.HasError == true)
                    {
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <p>@Model.Error</p>
                            <a class="btn btn-close" data-bs-dismiss="alert" arial-label="Close"></a>
                        </div>
                    }
                    
                    <p class="fs-3">Numero de tarjeta a la cual se pagara: @Model.NumeroTarjetaCredito</p>
                    
                    <div class="form-outline mb-4">
                        <label asp-for="NumeroCuentaOrigen" class="form-label">Cuenta Origen:</label>
                        <select class="form-select" asp-for="NumeroCuentaOrigen">
                            @foreach (CuentaAhorroViewModel item in ViewBag.listaCuentasAhorro)
                            {
                                <option value="@item.NumeroCuenta">@item.NumeroCuenta || $@item.Balance</option>
                            }
                        </select>
                    </div>

                    <div class="form-outline mb-4">
                        <p>Monto que posee la tarjeta actualmnete: @Model.TarjetaMonto</p>
                        <label asp-for="NumeroTarjetaCredito" class="form-label">Tarjeta:</label>
                        <input readonly asp-for="NumeroTarjetaCredito" value="@Model.NumeroTarjetaCredito" class="form-control"/>
                        <input type="hidden" asp-for="idTarjetaCredito" value="@Model.idTarjetaCredito" class="form-control"/>
                        <input type="hidden" asp-for="TarjetaMonto" value="@Model.TarjetaMonto" class="form-control"/>
                        <input type="hidden" asp-for="IdProduct" value="@Model.IdProduct" class="form-control"/>
                    </div>

                    <div class="form-outline mb-4">
                        <label asp-for="Monto" class="form-label">Monto a tomar de la tarjeta:</label>

                        <input class="form-control" asp-for="Monto" step="any" min="100" id="montoInput" placeholder="Monto">
                      
                      <p>se le suma un 6.25 % de interés del monto tomado prestado de la tarjeta de crédito</p>
                    </div>
                    
                    <button type="submit" class="btn btn-success btn-block mb-3">Obtener dinero</button>
                </div>
            </div>
        </form>
    </div>
</div>


@section scripts{
    <script>

        function commaOnly(input) {

            var value = input.val();
            var values = value.split("");
            var update = "";
            var transition = "";

            var expression = /(^\d+$)|(^\d+\.\d+$)|[,\.]/;
            var finalExpression = /^([1-9][0-9]*[,\.]?\d{0,3})$/;

            for (id in values) {
                if (expression.test(values[id]) == true && values[id] != '') {
                    transition += '' + values[id].replace('.', ',');
                    if (finalExpression.test(transition) == true) {
                        update += '' + values[id].replace('.', ',');
                    }
                }
            }
            input.val(update);
        }

        $('#montoInput').keyup(function (e) {
            commaOnly($(this));
        });

    </script>
}